#!/usr/bin/env python3
"""
Convert newsboat YouTube subscriptions to youtube-tui format.
Reads from ~/.newsboat/urls and writes to ~/.local/share/youtube-tui/subscriptions.json
"""

import json
import re
import os
from pathlib import Path

def parse_newsboat_urls(urls_path):
    """Extract YouTube channel IDs and names from newsboat urls file."""
    channels = []

    with open(urls_path, 'r') as f:
        for line in f:
            line = line.strip()
            # Skip empty lines, comments, and query feeds
            if not line or line.startswith('#') or line.startswith('"query:'):
                continue

            # Match YouTube feed URLs with channel IDs
            match = re.match(
                r'https://www\.youtube\.com/feeds/videos\.xml\?channel_id=([A-Za-z0-9_-]+)\s+"~([^"]+)"',
                line
            )
            if match:
                channel_id = match.group(1)
                channel_name = match.group(2)
                channels.append({
                    'id': channel_id,
                    'name': channel_name
                })

    return channels

def create_subscription_entry(channel_id, channel_name):
    """Create a youtube-tui subscription entry."""
    return {
        "channel": {
            "name": channel_name,
            "id": channel_id,
            "thumbnail_url": "",
            "sub_count": 0,
            "sub_count_text": "",
            "total_views": "0",
            "created": "",
            "autogenerated": False,
            "description": ""
        },
        "videos": [],
        "last_sync": 0,
        "last_sync_channel": 0,
        "has_new": False
    }

def main():
    # Paths
    newsboat_urls = Path.home() / ".newsboat" / "urls"
    # Also check stow location
    stow_urls = Path.home() / "dotfiles" / "newsboat" / ".newsboat" / "urls"

    if stow_urls.exists():
        urls_path = stow_urls
    elif newsboat_urls.exists():
        urls_path = newsboat_urls
    else:
        print("Error: Could not find newsboat urls file")
        return 1

    youtube_tui_path = Path.home() / ".local" / "share" / "youtube-tui" / "subscriptions.json"

    # Parse newsboat URLs
    channels = parse_newsboat_urls(urls_path)

    if not channels:
        print("No YouTube channels found in newsboat urls")
        return 1

    print(f"Found {len(channels)} YouTube channels:")
    for ch in channels:
        print(f"  - {ch['name']} ({ch['id']})")

    # Create subscription entries
    subscriptions = [
        create_subscription_entry(ch['id'], ch['name'])
        for ch in channels
    ]

    # Write to youtube-tui subscriptions.json
    youtube_tui_path.parent.mkdir(parents=True, exist_ok=True)
    with open(youtube_tui_path, 'w') as f:
        json.dump(subscriptions, f, indent=2)

    print(f"\nWritten {len(subscriptions)} subscriptions to {youtube_tui_path}")
    print("Open youtube-tui and go to Feeds to sync your subscriptions.")

if __name__ == "__main__":
    exit(main() or 0)
