# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#242426"
foreground = "#F3F0E5"
secondary_background = "#4A4A4C"
border = "#A19D93"
accent = "#978B5E"

[colors.accents]
blue = "#978B5E"
green = "#5C665E"
magenta = "#839FA0"
orange = "#997F7D"
purple = "#839FA0"
red = "#6B4B2F"
yellow = "#997F7D"
cyan = "#DDD3B6"

[colors.list.item.selection]
background = { name = "#978B5E", opacity = 0.3 }
secondary_background = "#A19D93"
foreground = "#978B5E"

[colors.list.item.hover]
background = { name = "#978B5E", opacity = 0.15 }
