# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#04000B"
foreground = "#FFF6F5"
secondary_background = "#04000B"
border = "#ACA3A2"
accent = "#AB9DB2"

[colors.accents]
blue = "#AB9DB2"
green = "#A6424E"
magenta = "#F69C9E"
orange = "#8D6488"
purple = "#F69C9E"
red = "#483761"
yellow = "#8D6488"
cyan = "#FEE4E2"

[colors.list.item.selection]
background = { name = "#AB9DB2", opacity = 0.3 }
secondary_background = "#ACA3A2"
foreground = "#AB9DB2"

[colors.list.item.hover]
background = { name = "#AB9DB2", opacity = 0.15 }
