# Wallust generated Vicinae theme

[meta]
version = 1
name = "Wallust"
description = "Dynamic colors from wallpaper"
variant = "dark"

[colors.core]
background = "#202121"
foreground = "#FBF3EF"
secondary_background = "#464747"
border = "#A8A09C"
accent = "#8A5F53"

[colors.accents]
blue = "#8A5F53"
green = "#41281A"
magenta = "#A29183"
orange = "#585649"
purple = "#A29183"
red = "#1C2221"
yellow = "#585649"
cyan = "#F3DCD0"

[colors.list.item.selection]
background = { name = "#8A5F53", opacity = 0.3 }
secondary_background = "#A8A09C"
foreground = "#8A5F53"

[colors.list.item.hover]
background = { name = "#8A5F53", opacity = 0.15 }
