# dconf-path: /org/gnome/desktop/interface/
[/]
accent-color='pink'
color-scheme='prefer-dark'
cursor-blink=true
cursor-blink-time=1000
cursor-size=24
cursor-theme='Catppuccin-Macchiato-Flamingo-Cursors'
document-font-name='JetBrains Mono  10'
enable-animations=true
font-name='JetBrains Mono  10'
gtk-theme='Breeze'
icon-theme='Catppuccin-Macchiato'
monospace-font-name='Hack  10'
scaling-factor=uint32 1
text-scaling-factor=1.0
toolbar-style='text'
