# dconf-path: /org/gnome/shell/
[/]
app-picker-layout=[{'Affinity.desktop': <{'position': <0>}>, 'org.gnome.Contacts.desktop': <{'position': <1>}>, 'org.gnome.Weather.desktop': <{'position': <2>}>, 'org.gnome.clocks.desktop': <{'position': <3>}>, 'org.gnome.Maps.desktop': <{'position': <4>}>, 'org.gnome.Music.desktop': <{'position': <5>}>, 'org.gnome.SimpleScan.desktop': <{'position': <6>}>, 'org.gnome.Settings.desktop': <{'position': <7>}>, 'Alacritty.desktop': <{'position': <8>}>, 'org.gnome.Showtime.desktop': <{'position': <9>}>, 'org.gnome.Snapshot.desktop': <{'position': <10>}>, 'org.gnome.Characters.desktop': <{'position': <11>}>, 'Utilities': <{'position': <12>}>, 'System': <{'position': <13>}>, 'org.gnome.Console.desktop': <{'position': <14>}>, 'org.gnome.Tour.desktop': <{'position': <15>}>, 'org.gnome.Yelp.desktop': <{'position': <16>}>, 'anchovy.desktop': <{'position': <17>}>, 'appimagelaunchersettings.desktop': <{'position': <18>}>, 'org.kde.ark.desktop': <{'position': <19>}>, 'bssh.desktop': <{'position': <20>}>, 'bvnc.desktop': <{'position': <21>}>, 'avahi-discover.desktop': <{'position': <22>}>, 'backup.desktop': <{'position': <23>}>}, {'appimagekit_8021073b25b7e878678393068ef0f554-balenaEtcher.desktop': <{'position': <0>}>, 'io.github.beacn_on_linux.beacn-utility.desktop': <{'position': <1>}>, 'btop.desktop': <{'position': <2>}>, 'btrfs-assistant.desktop': <{'position': <3>}>, 'arch-update.desktop': <{'position': <4>}>, 'cachyos-hello.desktop': <{'position': <5>}>, 'org.cachyos.KernelManager.desktop': <{'position': <6>}>, 'cachyos-pi.desktop': <{'position': <7>}>, 'Catppuccinifier.desktop': <{'position': <8>}>, 'cmake-gui.desktop': <{'position': <9>}>, 'code-oss.desktop': <{'position': <10>}>, 'conky.desktop': <{'position': <11>}>, 'curseforge.desktop': <{'position': <12>}>, 'discord.desktop': <{'position': <13>}>, 'org.gnome.Evince.desktop': <{'position': <14>}>, 'org.kde.dolphin.desktop': <{'position': <15>}>, 'org.gnome.Extensions.desktop': <{'position': <16>}>, 'org.kde.filelight.desktop': <{'position': <17>}>, 'firefox.desktop': <{'position': <18>}>, 'org.flameshot.Flameshot.desktop': <{'position': <19>}>, 'foot.desktop': <{'position': <20>}>, 'footclient.desktop': <{'position': <21>}>, 'foot-server.desktop': <{'position': <22>}>, 'org.gnome.Calculator.desktop': <{'position': <23>}>}, {'io.github.benjamimgois.goverlay.desktop': <{'position': <0>}>, 'org.kde.gwenview.desktop': <{'position': <1>}>, 'lstopo.desktop': <{'position': <2>}>, 'org.kde.haruna.desktop': <{'position': <3>}>, 'headcrab.desktop': <{'position': <4>}>, 'heroic.desktop': <{'position': <5>}>, 'htop.desktop': <{'position': <6>}>, 'org.kde.kate.desktop': <{'position': <7>}>, 'org.kde.kcalc.desktop': <{'position': <8>}>, 'org.kde.kdeconnect.app.desktop': <{'position': <9>}>, 'org.kde.kdeconnect.nonplasma.desktop': <{'position': <10>}>, 'org.kde.kdeconnect.sms.desktop': <{'position': <11>}>, 'org.kde.partitionmanager.desktop': <{'position': <12>}>, 'kdesystemsettings.desktop': <{'position': <13>}>, 'klassy-settings.desktop': <{'position': <14>}>, 'org.kde.konsole.desktop': <{'position': <15>}>, 'org.kde.kwalletmanager.desktop': <{'position': <16>}>, 'org.kde.kwrite.desktop': <{'position': <17>}>, 'limine-snapper-restore.desktop': <{'position': <18>}>, 'linutil.desktop': <{'position': <19>}>, 'net.lutris.Lutris.desktop': <{'position': <20>}>, 'org.gnome.TextEditor.desktop': <{'position': <21>}>}, {'mednaffe.desktop': <{'position': <0>}>, 'org.gnome.Meld.desktop': <{'position': <1>}>, 'micro.desktop': <{'position': <2>}>, 'mpv.desktop': <{'position': <3>}>, 'org.musicbrainz.Picard.desktop': <{'position': <4>}>, 'org.nicotine_plus.Nicotine.desktop': <{'position': <5>}>, 'nvidia-settings.desktop': <{'position': <6>}>, 'com.obsproject.Studio.desktop': <{'position': <7>}>, 'octopi.desktop': <{'position': <8>}>, 'octopi-cachecleaner.desktop': <{'position': <9>}>, 'octopi-notifier.desktop': <{'position': <10>}>, 'octopi-repoeditor.desktop': <{'position': <11>}>, 'onboard.desktop': <{'position': <12>}>, 'onboard-settings.desktop': <{'position': <13>}>, 'jconsole-java17-openjdk.desktop': <{'position': <14>}>, 'jshell-java17-openjdk.desktop': <{'position': <15>}>, 'org.openrgb.OpenRGB.desktop': <{'position': <16>}>, 'parsecd.desktop': <{'position': <17>}>, 'com.uploadedlobster.peek.desktop': <{'position': <18>}>, 'pipeweaver.desktop': <{'position': <19>}>, 'com.edde746.plezy.desktop': <{'position': <20>}>, 'org.prismlauncher.PrismLauncher.desktop': <{'position': <21>}>, 'project-lightning-v2.desktop': <{'position': <22>}>, 'appimagekit_119f68fea9a393fde3705e8bfc09b21e-Project_Lightning.desktop': <{'position': <23>}>}, {'protontricks.desktop': <{'position': <0>}>, 'assistant.desktop': <{'position': <1>}>, 'qdbusviewer.desktop': <{'position': <2>}>, 'linguist.desktop': <{'position': <3>}>, 'qv4l2.desktop': <{'position': <4>}>, 'qvidcap.desktop': <{'position': <5>}>, 'designer.desktop': <{'position': <6>}>, 'org.qutebrowser.qutebrowser.desktop': <{'position': <7>}>, 'rofi.desktop': <{'position': <8>}>, 'rofi-music.desktop': <{'position': <9>}>, 'rofi-theme-selector.desktop': <{'position': <10>}>, 'rustdesk.desktop': <{'position': <11>}>, 'org.cachyos.scx-manager.desktop': <{'position': <12>}>, 'com.shellyorg.shelly.desktop': <{'position': <13>}>, 'org.kde.spectacle.desktop': <{'position': <14>}>, 'steam.desktop': <{'position': <15>}>, 'steamidra.desktop': <{'position': <16>}>, 'appimagekit_ab4789f491a78f82693767e628f00fec-SteaMidra.desktop': <{'position': <17>}>, 'com.vixalien.sticky.desktop': <{'position': <18>}>, 'org.strawberrymusicplayer.strawberry.desktop': <{'position': <19>}>, 'org.kde.plasma-systemmonitor.desktop': <{'position': <20>}>, 'uuctl.desktop': <{'position': <21>}>, 'vesktop.desktop': <{'position': <22>}>, 'vicinae.desktop': <{'position': <23>}>}, {'vim.desktop': <{'position': <0>}>, 'virt-manager.desktop': <{'position': <1>}>, 'org.pulseaudio.pavucontrol.desktop': <{'position': <2>}>, 'appimagekit_5976c05da87740cfad6348e2d8d06ff7-Wago_App.desktop': <{'position': <3>}>, 'Wallpaper Engine.desktop': <{'position': <4>}>, 'wallpaper-picker.desktop': <{'position': <5>}>, 'appimagekit_34635d0ea493c5b8bd27dfa37310e1e3-winboat.desktop': <{'position': <6>}>, 'winetricks.desktop': <{'position': <7>}>, 'appimagekit_1c3adea977093584d3857fe1fd7bf6d2-WowUp-CF.desktop': <{'position': <8>}>, 'xgps.desktop': <{'position': <9>}>, 'xgpsspeed.desktop': <{'position': <10>}>, 'yazi.desktop': <{'position': <11>}>, 'youtube-music-desktop-app.desktop': <{'position': <12>}>, 'org.gnome.Epiphany.desktop': <{'position': <13>}>}]
enabled-extensions=['dash-to-dock@micxgx.gmail.com', 'blur-my-shell@aunetx']
favorite-apps=['librewolf.desktop', 'zen.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Software.desktop', 'io.github.Faugus.faugus-launcher.desktop', 'input-remapper-gtk.desktop', 'com.mitchellh.ghostty.desktop']
welcome-dialog-last-shown-version='50.4'

[extensions/blur-my-shell]
rounded-blur-found=false
settings-version=2

[extensions/blur-my-shell/appfolder]
brightness=0.59999999999999998
sigma=30

[extensions/blur-my-shell/applications]
blur=true
brightness=1.0
enable-all=true
pipeline='pipeline_default'
static-blur=false

[extensions/blur-my-shell/coverflow-alt-tab]
pipeline='pipeline_default'

[extensions/blur-my-shell/dash-to-dock]
blur=true
brightness=0.59999999999999998
pipeline='pipeline_default_rounded'
sigma=30
static-blur=false
style-dash-to-dock=0

[extensions/blur-my-shell/lockscreen]
pipeline='pipeline_default'

[extensions/blur-my-shell/overview]
pipeline='pipeline_default'
style-components=1

[extensions/blur-my-shell/panel]
brightness=0.58999999999999997
corner-radius=0
pipeline='pipeline_default'
sigma=30
static-blur=false

[extensions/blur-my-shell/screenshot]
pipeline='pipeline_default'

[extensions/blur-my-shell/window-list]
brightness=0.59999999999999998
sigma=30

[extensions/dash-to-dock]
apply-custom-theme=false
autohide=false
background-opacity=0.80000000000000004
click-action='minimize-or-overview'
custom-theme-shrink=true
dash-max-icon-size=48
dock-fixed=true
dock-position='LEFT'
extend-height=true
height-fraction=0.90000000000000002
intellihide=false
max-alpha=0.80000000000000004
preferred-monitor=-2
preferred-monitor-by-connector='DP-2'
running-indicator-style='DOTS'
scroll-action='cycle-windows'
transparency-mode='DYNAMIC'

[world-clocks]
locations=@av []
