# dconf-path: /org/gnome/shell/
[/]
enabled-extensions=['dash-to-dock@micxgx.gmail.com']
welcome-dialog-last-shown-version='50.4'

[extensions/dash-to-dock]
apply-custom-theme=false
autohide=false
background-opacity=0.80000000000000004
click-action='minimize-or-overview'
custom-theme-shrink=true
dash-max-icon-size=48
dock-fixed=true
dock-position='LEFT'
extend-height=true
height-fraction=0.90000000000000002
intellihide=false
max-alpha=0.80000000000000004
preferred-monitor=-2
preferred-monitor-by-connector='DP-2'
running-indicator-style='DOTS'
scroll-action='cycle-windows'
transparency-mode='DYNAMIC'

[world-clocks]
locations=@av []
